general.import = ["~/.config/alacritty/themes/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
padding.x = 5
padding.y = 5
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"

[font]
normal.family = "Hasklug Nerd Font Mono"
size = 10

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux; exec /bin/zsh -l"]
